# Generated by Django 5.1.2 on 2025-11-09 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='type_charge',
            field=models.CharField(choices=[('fournisseur', 'Charge fournisseur'), ('salariale', 'Charge salariale'), ('fixe', 'Charge fixe'), ('patronale', 'Charge patronale')], max_length=20),
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='description',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='date_depense',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='note',
        ),
        migrations.AddField(
            model_name='charge',
            name='autres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='categorie_fixe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='cnss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='employe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='mois',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='charge',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='charge',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='charge',
            name='primes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='remuneration_gerant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='salaire_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='TypeCharge',
        ),
    ]
