# Generated by Django 5.2.7 on 2025-10-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.client'),
        ),
    ]
