# Generated by Django 5.1.2 on 2025-11-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boncommandes', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bl', models.CharField(max_length=50, unique=True)),
                ('date_livraison', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('partielle', 'Partielle'), ('complete', 'Complète')], default='partielle', max_length=20)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='boncommandes.boncommande')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bonlivraisons.bonlivraison')),
            ],
        ),
    ]
