# Generated by Django 5.1.2 on 2025-11-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
