# Generated by Django 5.2.7 on 2025-10-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_remove_fournisseur_email_remove_fournisseur_statut_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='fournisseurs.fournisseur'),
        ),
    ]
