# Generated by Django 5.2.7 on 2025-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_article_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
