# Generated by Django 5.1.2 on 2025-11-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ice', models.CharField(max_length=20, unique=True)),
                ('if_fiscal', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_facture', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paiement_restant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('non_payee', 'Non payée'), ('partielle', 'Partielle'), ('payee', 'Payée')], default='non_payee', max_length=20)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='fournisseurs.facturefournisseur')),
            ],
        ),
    ]
