# Generated by Django 5.2.7 on 2025-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='telephone',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='historique_livraison',
            field=models.TextField(blank=True, null=True),
        ),
    ]
