# Generated by Django 5.1.2 on 2025-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_remove_fournisseur_email_remove_fournisseur_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='historique_livraison',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='solde',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ice',
            field=models.CharField(default='0000000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='if_fiscal',
            field=models.CharField(default='0000000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
    ]
